---

- name: Test different than node
  command: touch /home/vagrant/IAMCONTROLLER

- name: Start the kubeadm initialization
  command: kubeadm init --apiserver-advertise-address=192.168.56.3
  args:
    creates: /etc/kubernetes/admin.conf

- name: Change permissions of admin.conf.
  command: chmod 777 /etc/kubernetes/admin.conf

- name: make .kube folder
  command: mkdir -p "~/.kube"
  become_user: "vagrant"
# -n option should be changed to a makes file -> it is depricated behaviour ... 
- name: Copy admin kubeconfig file
  command: cp -i -n /etc/kubernetes/admin.conf ~/.kube/config
  become_user: "vagrant"

- name: Deploy Calico network
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  become_user: "vagrant"

- name: Export the kubeadm join command for nodes
  command: kubeadm token create --print-join-command
  register: join_command_output

#- debug:
#    var: join_command_output.stdout

- name: Get localhost user
  set_fact:
    playbook_user: "{{ lookup('env', 'USER') }}"

- debug:
    var: playbook_user

- name: Write command to file
  copy:
    content: "{{ join_command_output.stdout }}"
    dest: /tmp/joincommand.txt
  #become: yes
  delegate_to: localhost
  become_user: "{{ playbook_user }}"