# docker-compose.yml

services: 
  app-service: 
    build: 
      context: ../app
      dockerfile: Dockerfile
    ports: 
    - "8080:8080"
    volumes: 
      # - ./html:/usr/share/nginx/html
      - ../app/app-service:/app/app-service
      - ../app/app-frontend:/app/app-frontend

  model-service:
    build: 
      context: ../model-service
      dockerfile: Dockerfile
    ports: 
      - "6000:6000"
    # environment: 
      # - config=./../model-training/config.yml
    volumes: 
      - ../model-training/models:/app/models
  proxy: 
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-service
      - model-service