version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 on the host and forward to port 80 on the nginx container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

  model-service:
    #build:
    #  context: ../model-service/
    #  dockerfile: Dockerfile
    image: ghcr.io/remla24-team-1/model-service:latest
    networks:
      - webnet
    expose:
      - "8081"  # Makes port 8081 available to linked services but not to the outside world

  app-service:
    image: ghcr.io/remla24-team-1/app:latest
    networks:
      - webnet
    ports:
      - "8080:8080"  # Expose port 8080 on the host and forward to port 8080 on the container
    environment:
      - MODEL_SERVICE_URL=http://model-service:8081

networks:
  webnet: # Defines a network named webnet for communication between containers