# docker-compose.yml

services: 
  app-service: 
    image: nginx:latest
    ports: 
    - "8080:80"
    volumes: 
      - ./html:/usr/share/nginx/html

  model-service:
    build: 
      context: ../model-service
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    # environment: 
      # - config=./../model-training/config.yml
    volumes: 
      - ../model-training/models:/app/models
  proxy: 
    image: nginx:latest
    ports: 
      - "8081:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf  # Mount the specific file
    depends_on:
      - app-service
      - model-service