---
 # Add all to common group, which will execute playbook in roles/common/tasks/main.yml automatically
- hosts: all
  become: yes
  roles:
  - common

# If it is part of the nodes ansible group, the VM will execute stuff in the roles/nodes
- hosts: nodes
  become: true
  roles:
   - nodes
  
# Same but for the controller 
- hosts: controllers
  become: yes
  roles:
   - controllers


#- name: JOIN controller command
#  hosts: controller
#  tasks:
#    - name: Export the kubeadm join command for nodes
#      command: kubeadm token create --print-join-command
#      register: join_command_output

#- name: JOIN node command
#  hosts: nodes
#  tasks:
#    - name: JOIN
#      command: "{{ join_command_output.stdout }}"