{
 "title": "Remla01",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "URL checks amount",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "url_check_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Visitors Today",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "visit_count_today", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "URL duration summary",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "check_url_duration_summary", "legendFormat": "{{quantile}}" }
   ]
  },
  {
   "title": "URL duration in seconds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "check_url_duration", "legendFormat": "{{le}}" }
   ]
  }
 ]
}