---
#- name: Test initialization differnet than controller
#  command: touch /home/vagrant/IAMNODE- name: Get the user running the playbook  

- name: Get localhost user
  set_fact:
    playbook_user: "{{ lookup('env', 'USER') }}"

- debug:
    var: playbook_user

- name: Get command from file
  slurp:
    src: "/tmp/joincommand.txt"
  delegate_to: localhost
  become_user: "{{ playbook_user }}"
  register: JOINCOMMAND

- debug:
    var: JOINCOMMAND.content

- name: Decode the command
  set_fact:
    decoded_command: "{{ JOINCOMMAND.content | b64decode }}"

- debug:
    var: decoded_command

- name: Join the cluster.
  shell: "{{ decoded_command }}"
  register: commandres

- debug:
    var: commandres