apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "ghcr.io/remla24-team-1/app:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MODEL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: MODEL_SERVICE_URL
