apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-deployment
  labels:
    app: model-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: "ghcr.io/remla24-team-1/model-service:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
