apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        exact: /prometheus
    rewrite:
      uri: /
    route:
    - destination:
        host: prometheus-server.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /prometheus/
    rewrite:
      uri: /
    route:
    - destination:
        host: prometheus-server.default.svc.cluster.local
        port:
          number: 80